modLoader="javafml"
loaderVersion="[52,)"
license="MIT"
# logoFile="nativenature_logo.png"

[[mods]]
modId="nativenature"
version="1.1.0-1.21.1"
displayName="Native Nature"
logoFile="nativenature_logo.png"
authors="zzzaitegui"
description='''
Craft biome-locked vegetation that preserves its natural coloration when placed in different biomes.
Build diverse zoos, gardens, and habitats without color mismatches.
'''

[[dependencies.nativenature]]
modId="forge"
mandatory=true
versionRange="[52,)"
ordering="NONE"
side="BOTH"

[[dependencies.nativenature]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"